config/routes.rb
OrderDemo::Application.routes.draw do
  get "home/index"

  resources :orders

  resources :line_items

  resources :products do
    collection do
        get 'product_details'
       
     end
   end

  resources :addresses do
    collection do
        get 'address_count'
     end
   end

  resources :customers do
    collection do
        get 'customer_details'
         get 'customer_address'
     end
   end
root to: "home#index"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	attr_accessible :email, :mobile, :first_name, :last_name
	attr_accessible :addresses_attributes
	has_many :addresses, :dependent => :destroy
	has_many :orders
	accepts_nested_attributes_for :addresses, :allow_destroy => true
	validates :email, :mobile, :first_name, :last_name,  presence: true
	validates :mobile, numericality: true
	#validates_uniqueness_of :email
	validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
# GET /customers
# GET /customers.json
def index
  @customers = Customer.all

  respond_to do |format|
format.html # index.html.erb
format.json { render json: @customers }
end
end

# GET /customers/1
# GET /customers/1.json
def show

  if request.xhr?
    @customer = Customer.find_by_email(params[:email])
  else
    @customer = Customer.find(params[:id])  #Customer.includes(:addresses).find(params[:id])
    @addresses = @customer.addresses
  end
respond_to do |format|
format.html # show.html.erb
format.json { render json: @customer }
end
end

# GET /customers/new
# GET /customers/new.json
def new
  @customer = Customer.new
 # @address = @customer.addresses.new
 # @order = @customer.orders.new

  respond_to do |format|
format.html # new.html.erb
format.json { render json: @customer }
end
end

def customer_details  
  @customer = Customer.find_by_email(params[:email])
  respond_to do |format|
format.html # show.html.erb
format.json { render json: @customer }
end
end


def customer_address

  @customer = Customer.find_by_email(params[:email])
  #@id = @customer.id
  @add = @customer.addresses
  respond_to do |format|
format.html # show.html.erb
format.json { render json: @add }

end
end
# GET /customers/1/edit
def edit
  @customer = Customer.find(params[:id])

end

# POST /customers
# POST /customers.json
def create
  #raise params.inspect
  
  @customer = Customer.new(params[:customer])
  # my_class = Customer.find_or_initialize_by_email(params[:customer])
  #@customer.addresses.build
# @customer.order.build
if Customer.where(email: @customer.email).empty?
  respond_to do |format|
    if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render json: @customer, status: :created, location: @customer }
    else
        format.html { render action: "new" }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
    end
  end
else
  flash[:notice] = 'Customer already Exists'
  render action: "new" , flash: {notice: "Customer already Exists"} 

end
end
# end

# PUT /customers/1
# PUT /customers/1.json
def update
  @customer = Customer.find(params[:id])

  respond_to do |format|
    if @customer.update_attributes(params[:customer])
      format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
      format.json { head :no_content }
    else
      format.html { render action: "edit" }
      format.json { render json: @customer.errors, status: :unprocessable_entity }
    end
  end
end

# DELETE /customers/1
# DELETE /customers/1.json
def destroy
  @customer = Customer.find(params[:id])
  @customer.destroy

  respond_to do |format|
    format.html { redirect_to customers_url }
    format.json { head :no_content }
  end
end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_address_fields.html.erb
<div class="panel panel-default">

    <div class="panel-heading">Address Details
    <div align="right"><%= link_to_remove_fields "remove", f %></div>
</div>
    <div class="panel-body">
<div class="row">
<div class="col-sm-3">
  <%= f.label :street_no %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :street_no , :required => true%>
</div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :street_name %>
 </div>
  <div class="col-sm-6">
  <%= f.text_field :street_name, :required => true %>
  </div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :area_name %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :area_name, :required => true %>
 </div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :landmark %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :landmark , :required => true%>
 </div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :city %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :city, :required => true %>
  </div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :postal_code %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :postal_code, :required => true %>
  </div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :state %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :state , :required => true%>
 </div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :country %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :country, :required => true %>
</div>
</div>
</div>
</div>

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
<% if @customer.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

  <ul>
    <% @customer.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="panel panel-default">
    <div class="panel-heading">Customer Details</div>
    <div class="panel-body">
<div class="row">
  <div class="col-sm-3">
    <%= f.label :first_name, :required => true %>
  </div>
  <div class="col-sm-6">
    <%= f.text_field :first_name , :required => true%>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= f.label :last_name, :required => true %>
  </div>
  <div class="col-sm-6">
    <%= f.text_field :last_name, :required => true %>
  </div>
</div>

<div class="row">
  <div class="col-sm-3">
    <%= f.label :mobile, :required => true %>
  </div>
  <div class="col-sm-6">
    <%= f.text_field :mobile, :required => true %>
  </div>
</div>
<div class="row">
  <div class="col-sm-3">
    <%= f.label :email %>
  </div>
<div class="col-sm-6">
  <%= f.text_field :email, :required => true %>
</div>
</div>
<br/>
<br/>

<div class="panel panel-default">
    <div class="panel-heading">Customer Addresses</div>
    <div class="panel-body">
<%= f.fields_for :addresses do |builder| %>
<%=  render 'address_fields', :f => builder %>
<% end %>
<%= link_to_add_fields "Add Address", f, :addresses %>
</div>
</div>

<div class="actions">
 <%= button_tag( :class => 'btn btn-primary', :title => 'Save', :rel => 'tooltip') do %>
       Save<span class="glyphicon glyphicon-floppy-save"></span> 
   <% end %>
</div>
</div>
  </div>
<% end %>

app/views/customers/_order.html.erb
<div class="row">
<div class="col-sm-3">
 <%= f.label :order_no %>
  </div>
  <div class="col-sm-6">
   <%= f.text_field :order_no , :required => true%>
</div>
</div>

<div class="row">
<div class="col-sm-3">
 <%= f.label :tracking_no %>
 </div>
  <div class="col-sm-6">
   <%= f.text_field :tracking_no , :required => true%>
  </div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :delivery_date %>
  </div>
  <div class="col-sm-6">
  <%= f.date_select :delivery_date, :required => true %>
 </div>
</div>

<div class="row">
<div class="col-sm-3">
 
  </div>
  <div class="col-sm-6">
  <%= f.check_box :is_express_delivery %>
   <%= f.label :is_express_delivery %>
 </div>
</div>

<div class="row">
<div class="col-sm-3">
 
  </div>
  <div class="col-sm-6">
 
 <%= f.check_box :is_customer_pickup %>
  <%= f.label :is_customer_pickup %>
  </div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :delivery_slot %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :delivery_slot, :required => true %>
  </div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :carrier %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :carrier, :required => true %>
 </div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :order_currency %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :order_currency , :required => true%>
</div>
</div>


<div class="row">
<div class="col-sm-3">
  <%= f.label :order_value %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :order_value, :required => true %>
</div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :payment_collection %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :payment_collection , :required => true%>
</div>
</div>

<div class="row">
<div class="col-sm-3">
  <%= f.label :special_instruction %>
  </div>
  <div class="col-sm-6">
  <%= f.text_field :special_instruction, :required => true %>
</div>
</div>

app/views/customers/edit.html.erb
<div class="row">
  <br/><br/>
  <br/>
</div>
<div class = "form_content">
 <h1 style="color:white;">Editing customer</h1>


<%= link_to  @customer, :class => 'btn  btn-warning',:title => 'Show', :rel => 'tooltip' do%>
              <span class="glyphicon glyphicon-eye-open"></span> Show
              <%end%>
<%= link_to  customers_path , class: "btn btn-default", :title => 'Back', :rel => 'tooltip' do %>
<span class="glyphicon glyphicon-step-backward"></span> Back
<% end %>
<%= render 'form' %>

</div>

app/views/customers/index.html.erb
<div class="row">
  <br/><br/>
  <br/>
</div>
<div class="row">
  <div class="col-md-12">
    <h1 style="color:white;">Listing customers</h1>
    <br />
    <%= link_to new_customer_path, :class => 'btn btn-md btn-default',:title => 'Add New Customer', :rel => 'tooltip' do %>
    <span class="glyphicon glyphicon-user"></span> New Customer 
    <% end %>
    <br /><br />
    <table class="table table-striped table-hovered" id="t01">
      <tr>
        <th>First Name</th>
        <th>last Name</th>
        <th>Mobile</th>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>

      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.mobile %></td>
        <td><%= customer.email %></td>

        <td><%= link_to customer_path(customer), :class => 'btn btn-xs btn-warning',:title => 'Show', :rel => 'tooltip' do%>
              <span class="glyphicon glyphicon-eye-open"></span> Show
              <%end%></td>
        <td><%= link_to edit_customer_path(customer),:class => 'btn btn-xs btn-info',:title => 'Edit', :rel => 'tooltip' do %>
              <span class="glyphicon glyphicon-edit"></span> Edit  
              <% end %></td>
        <td><%= link_to customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' } , :class => 'btn btn-xs btn-danger', :title => 'Delete', :rel => 'tooltip' do %>
              <span class="glyphicon glyphicon-trash"></span> Remove  
              <% end %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/customers/new.html.erb
<div class="row">
  <br/><br/>
  <br/>
</div>
<div class = "form_content">
<h1 style="color:white;">New customer</h1>
<%= link_to  customers_path , class: "btn btn-default", :title => 'Back', :rel => 'tooltip' do %>
<span class="glyphicon glyphicon-step-backward"></span> Back
<% end %>
<%= render 'form' %>
</div>

app/views/customers/show.html.erb
<div class="row">
  <br/><br/>
  <br/>
</div>

<p id="notice"><%= notice %></p>
	<div class="panel panel-default">
			<div class="panel-heading"><h3><%= @customer.first_name %> <%=  @customer.last_name %></h3><div align="right"><%= link_to  edit_customer_path(@customer) ,:class => 'btn btn-info',:title => 'Edit', :rel => 'tooltip' do %>

              <span class="glyphicon glyphicon-edit"></span> Edit  
              <% end %>
<%= link_to  customers_path , class: "btn btn-default", :title => 'Back', :rel => 'tooltip' do %>
<span class="glyphicon glyphicon-step-backward"></span> Back
<% end %></div></div>
			<div class="panel-body">
<p>
  <b>First Name:</b>
  <%= @customer.first_name %>
</p>
<p>
  <b>Last Name:</b>
  <%= @customer.last_name %>
</p>

<p>
  <b>Mobile:</b>
  <%= @customer.mobile %>
</p>

<p>
  <b>Email:</b>
  <%= @customer.email %>
</p>

<div class="row">
	<% @addresses.each_with_index do |add, index| %>
	<div class="col-sm-4">
		<div class="panel panel-default">
			<div class="panel-heading"> <h6><b>Address No. <%= index + 1%></b></h6></div>
			<div class="panel-body">

					<p>
						<b>Street name:</b>
						<%= add.street_name %>
					</p>

					<p>
						<b>Area name:</b>
						<%= add.area_name %>
					</p>

					<p>
						<b>Landmark:</b>
						<%= add.landmark %>
					</p>

					<p>
						<b>City:</b>
						<%= add.city %>
					</p>

					<p>
						<b>Postal code:</b>
						<%= add.postal_code %>
					</p>

					<p>
						<b>State:</b>
						<%= add.state %>
					</p>

					<p>
						<b>Country:</b>
						<%= add.country %>
					</p>

					<p>
						<b>Street no:</b>
						<%= add.street_no %>
					</p>

				</div>
			</div>
		</div>
		 <% end %>
	</div>
 
</div>
</div>