config/routes.rb
OrderDemo::Application.routes.draw do
  get "home/index"

  resources :orders

  resources :line_items

  resources :products do
    collection do
        get 'product_details'
       
     end
   end

  resources :addresses do
    collection do
        get 'address_count'
     end
   end

  resources :customers do
    collection do
        get 'customer_details'
         get 'customer_address'
     end
   end
root to: "home#index"

end

app/views/layouts/_carousel.html.erb
<br/><br/><br/><br/>



<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item  active">
      <img src="http://www.therma-store.com/images/banner-shop4.jpg" alt="Flower" width="460" height="200">
      <div class="carousel-caption">
        <!-- <font color="black"><h3>KNOWLEDGE</h3></font> -->
      </div>
    </div>


    <div class="item">
      <img src="http://3.bp.blogspot.com/-rjluK0oy8Do/VRJBJoC8pNI/AAAAAAAAAEk/taC_y6VXldE/s1600/1422960774614.png" alt="Flower" width="460" height="200">
      <div class="carousel-caption">
        <!-- <font color="black"><h3>KNOWLEDGE</h3></font> -->
      </div>
    </div>

    <div class="item">
      <img src="http://www.inizinfotech.com/wp-content/uploads/2014/07/e-commerce-banner.jpg" alt="Chania" width="460" height="200">
      <div class="carousel-caption">
        <!-- <font color="black"><h3>KNOWLEDGE</h3></font> -->
        </div>
    </div>
     <div class="item">
      <img src="http://www.nigerdeltawealthcreation.org/wp-content/uploads/2016/01/shop.png" alt="Chania" width="460" height="200">
      <div class="carousel-caption">
        <!-- <font color="black"><h3>KNOWLEDGE</h3></font> -->
      </div>
    </div>


  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/_flash.html.erb
<% if notice || alert %>
  <div class="flash-message <%= notice ? "notice" : ""%><%= alert ? "error" : ""%>">
    <div class="container container_12 clearfix">
      <div class="grid_12">
        <% if notice %>
          <p><%= notice %></p>
        <% elsif alert %>
          <p><%= alert %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="row">
  <div class="col-md-3">
    <font color= "black">Developed By : Dhanashri Joshi</font>
  </div>
  <div class="col-md-3 col-md-push-6">
   <ul class="nav navbar-nav navbar-right">
      <li></li>
      <li></li>
      <li><a href="http://www.anchanto.com/">Anchanto</a></li>
    </ul>
  
  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<header style="background-color:black;">
<nav class="navbar navbar-inverse navbar-fixed-top">
  
    <div class="navbar-header">
      <a class="navbar-brand" style="color:white;"><h4>MyCart</h4></a>
    </div>
    <ul class="nav navbar-nav  navbar-right" style="padding-right: 20px">
      <li class="active"><%= link_to "Home", root_path %></li>
     <li><%= link_to 'Customers', customers_path %></li>
        <li><%= link_to 'Addresses' , addresses_path %></li>
        <li><%= link_to 'Products' , products_path %></li>         
        <li><%= link_to 'Orders' , orders_path %></li> 
    </ul>
 
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Cart</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag 'jquery.min', 'jquery-ui-1.8.2.custom.min.js' %>
  <%= stylesheet_link_tag 'cupertino/jquery-ui-1.8.2.custom' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'fav1.ico' %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
<script src="assets/sweetalert.min.js"></script>
  <link rel="stylesheet" type="text/css" href="assets/sweetalert.css">
  <style>
    .carousel-inner > .item > img,
    .carousel-inner > .item > a > img {
      width: 60%;

      margin: auto;
    }
  </style>
</head>
<body>

  <div class="container-fluid">
    <%= render 'layouts/header' %>
    <div class="row">
      <div class="col-md-12">
        <% flash.each do |name, msg| %>
<%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

        <%= yield %>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </div>

</body>
</html>